enhancement/add-www-index
highcharts/highcharts-dist pull request #22
Opened 2024-02-07 09:01 UTC by goransle

2024-02-19 15:18 UTC, oysteinmoseng requested changes
Just sneaking in a license text update while we are at it.

2024-02-19 15:18 UTC, oysteinmoseng commented on www/index.html
> +<p><i>Please feel free to link to the files from our CDN at code.highcharts.com. The files are hosted from Cloudflare, which distributes them to edge locations all over the world for fast access and
Add this paragraph while we are at it:

> Note that when retrieving Highcharts code via our CDN, you automatically access the most up-to-date version of our software. To qualify for this benefit, you must maintain an active Highcharts Advantage plan.
If you're uncertain about the specific Highcharts version covered by your license, please refer to your License Statement provided at the time of purchase. Alternatively, you can reach out to our sales team at [sales@highsoft.com](mailto:sales@highsoft.com), and we will gladly verify the information for you.

2024-02-21 14:20 UTC, oysteinmoseng approved these changes

2024-02-27 12:48 UTC, goransle commented
Replaced by https://github.com/highcharts/highcharts/pull/20725

2024-02-27 12:48 UTC, closed without merging